# LOWESS Trend Decomposition

import json
import pandas as pd

In [4]:
with open('./data/KTA354XA_trip_01.json') as f:
    d = json.load(f)

df = pd.json_normalize(d)
df = df.rename(columns={"attributes.adc1":"adc", 'attributes.battery':'battery', 'attributes.power':'power','attributes.totalDistance':'totalDistance'}, errors='raise')
df['deviceTime'] = pd.to_datetime(df['deviceTime'])
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1154 entries, 0 to 1153
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1154 non-null   int64
 1   deviceId              1154 non-null   int64
 2   type                  0 non-null      object
 3   protocol              1154 non-null   object
 4   serverTime            1154 non-null   object
 5   deviceTime            1154 non-null   datetime64[ns, UTC]
 6   fixTime               1154 non-null   object
 7   outdated              1154 non-null   bool
 8   valid                 1154 non-null   bool
 9   latitude              1154 non-null   float64
 10  longitude             1154 non-null   float64
 11  altitude              1154 non-null   float64
 12  speed                 1154 non-null   float64
 13  course                1154 non-null   float64
 14  address               0 non-null      object
 15  accuracy              1154 non-null   float64
 16  network               0 non-null      object
 17  attributes.priority   1154 non-null   int64
 18  attributes.sat        1154 non-null   int64
 19  attributes.event      1154 non-null   int64
 20  attributes.ignition   1154 non-null   bool
 21  attributes.motion     1154 non-null   bool
 22  attributes.rssi       1154 non-null   int64
 23  attributes.io200      1154 non-null   int64
 24  attributes.gpsStatus  1154 non-null   int64
 25  attributes.pdop       1154 non-null   float64
 26  attributes.hdop       1154 non-null   float64
 27  power                 1154 non-null   float64
 28  battery               1154 non-null   float64
 29  attributes.io68       1154 non-null   int64
 30  adc                   1154 non-null   int64
 31  attributes.operator   1154 non-null   int64
 32  attributes.odometer   1154 non-null   int64
 33  attributes.distance   1154 non-null   float64
 34  totalDistance         1154 non-null   float64
 35  attributes.hours      1154 non-null   int64
dtypes: bool(4), datetime64[ns, UTC](1), float64(12), int64(13), object(6)
memory usage: 293.1+ KB

,id,deviceId,type,protocol,serverTime,deviceTime,fixTime,outdated,valid,latitude,...,attributes.hdop,power,battery,attributes.io68,adc,attributes.operator,attributes.odometer,attributes.distance,totalDistance,attributes.hours
0,5731642,35,None,teltonika,2021-08-16T05:32:07.149+00:00,2021-08-16 05:32:04+00:00,2021-08-16T05:32:04.000+00:00,False,True,5.070095,...,0.3,25.353,4.038,0,2549,62130,4168377,0.0,4164234.18,686730980
1,5731656,35,None,teltonika,2021-08-16T05:32:13.924+00:00,2021-08-16 05:32:11+00:00,2021-08-16T05:32:11.000+00:00,False,True,5.070095,...,0.3,25.292,4.040,0,2549,62130,4168377,0.0,4164234.18,686730980
2,5731699,35,None,teltonika,2021-08-16T05:32:37.871+00:00,2021-08-16 05:32:35+00:00,2021-08-16T05:32:35.000+00:00,False,True,5.070095,...,0.3,28.044,4.038,0,2549,62130,4168377,0.0,4164234.18,686754980
3,5731806,35,None,teltonika,2021-08-16T05:33:37.869+00:00,2021-08-16 05:33:35+00:00,2021-08-16T05:33:35.000+00:00,False,True,5.070095,...,0.3,28.383,4.038,0,2549,62130,4168377,0.0,4164234.18,686814980
4,5731900,35,None,teltonika,2021-08-16T05:34:38.727+00:00,2021-08-16 05:34:36+00:00,2021-08-16T05:34:36.000+00:00,False,True,5.070095,...,0.3,28.391,4.038,0,2549,62130,4168377,0.0,4164234.18,686875980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1149,5750440,35,None,teltonika,2021-08-16T07:40:14.839+00:00,2021-08-16 07:40:12+00:00,2021-08-16T07:40:12.000+00:00,False,True,5.009142,...,0.3,26.848,4.038,0,2637,62130,4214166,0.0,4209930.89,693846980
1150,5750452,35,None,teltonika,2021-08-16T07:40:24.818+00:00,2021-08-16 07:40:22+00:00,2021-08-16T07:40:22.000+00:00,False,True,5.009142,...,0.3,26.806,4.038,0,2637,62130,4214166,0.0,4209930.89,693846980
1151,5750474,35,None,teltonika,2021-08-16T07:40:34.818+00:00,2021-08-16 07:40:32+00:00,2021-08-16T07:40:32.000+00:00,False,True,5.009142,...,0.3,26.762,4.038,0,2637,62130,4214166,0.0,4209930.89,693846980
1152,5750495,35,None,teltonika,2021-08-16T07:40:44.843+00:00,2021-08-16 07:40:42+00:00,2021-08-16T07:40:42.000+00:00,False,True,5.009142,...,0.3,26.729,4.038,0,2637,62130,4214166,0.0,4209930.89,693846980
1153,5750515,35,None,teltonika,2021-08-16T07:40:56.980+00:00,2021-08-16 07:40:52+00:00,2021-08-16T07:40:52.000+00:00,False,True,5.009142,...,0.4,26.711,4.038,0,2637,62130,4214166,0.0,4209930.89,693846980